---
apiVersion: v1
kind: Namespace
metadata:
  name: springboot
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: springboot
  labels:
    app: spring-boot
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: spring-boot
  type: LoadBalancer
---           
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  namespace: springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
      - image: aksregistryuseast.azurecr.io/spring-boot-docker:20
        imagePullPolicy: Always
        name: spring-boot
        ports:
        - containerPort: 8080
          name: spring-boot
      imagePullSecrets:
      - name: aksregistrysecret